version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

executors:
  default:
    machine: true
    environment:
      ECR_REPO: 'test-ecs-log'
      AWS_ECR_ACCOUNT_URL: '<your_account_id>.dkr.ecr.ap-northeast-1.amazonaws.com'
      AWS_REGION: 'ap-northeast-1'
      CLUSTER_NAME: 'test-cluster'

workflows:
  build-push:
    jobs:
      - aws-ecr/build_and_push_image:
          name: 'build-latest'
          executor: default
          repo: '${ECR_REPO}'
          tag: 'latest'
